-- MySQL Script generated by MySQL Workbench
-- Sun Feb 11 15:03:14 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema 24769562_dariusz
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 24769562_dariusz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `24769562_dariusz` DEFAULT CHARACTER SET latin2 ;
USE `24769562_dariusz` ;

-- -----------------------------------------------------
-- Table `24769562_dariusz`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `24769562_dariusz`.`customers` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `24769562_dariusz`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `24769562_dariusz`.`orders` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `customer` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `customer_fk_idx` (`customer` ASC),
  CONSTRAINT `customer_fk`
    FOREIGN KEY (`customer`)
    REFERENCES `24769562_dariusz`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `24769562_dariusz`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `24769562_dariusz`.`items` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `order` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `order_fk_idx` (`order` ASC),
  CONSTRAINT `order_fk`
    FOREIGN KEY (`order`)
    REFERENCES `24769562_dariusz`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `24769562_dariusz`.`Numer VIN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `24769562_dariusz`.`Numer VIN` (
  `idNumer` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Numer VIN` INT UNSIGNED NULL,
  `idCar` INT NOT NULL,
  PRIMARY KEY (`idNumer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `24769562_dariusz`.`Ubezpieczenie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `24769562_dariusz`.`Ubezpieczenie` (
  `idUbezpieczenie` INT NOT NULL AUTO_INCREMENT,
  `Ubezpieczenie` INT UNSIGNED NULL,
  PRIMARY KEY (`idUbezpieczenie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `24769562_dariusz`.`MarkaSamochodu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `24769562_dariusz`.`MarkaSamochodu` (
  `idMarkaSamochodu` INT NOT NULL AUTO_INCREMENT,
  `MarkaSamochodu` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMarkaSamochodu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `24769562_dariusz`.`ModelSamochodu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `24769562_dariusz`.`ModelSamochodu` (
  `idModelSamochodu` INT NOT NULL AUTO_INCREMENT,
  `ModelSamochodu` VARCHAR(45) NOT NULL,
  `MarkaSamochodu` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idModelSamochodu`),
  CONSTRAINT `markaSamochodu`
    FOREIGN KEY (`idModelSamochodu`)
    REFERENCES `24769562_dariusz`.`MarkaSamochodu` (`idMarkaSamochodu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `24769562_dariusz`.`Auta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `24769562_dariusz`.`Auta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(45) NOT NULL,
  `rocznik` INT NOT NULL,
  `moc` INT NOT NULL,
  `kolor` VARCHAR(45) NOT NULL,
  `ilosc drzwi` INT NOT NULL,
  `idVin` INT UNSIGNED NULL,
  `ubezpieczenie` INT NOT NULL,
  `cenaBrutto` FLOAT NOT NULL,
  `cenaNetto` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `NumerVin_idx` (`idVin` ASC),
  INDEX `ubezpieczenie_idx` (`ubezpieczenie` ASC),
  CONSTRAINT `NumerVin`
    FOREIGN KEY (`idVin`)
    REFERENCES `24769562_dariusz`.`Numer VIN` (`idNumer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ubezpieczenie`
    FOREIGN KEY (`ubezpieczenie`)
    REFERENCES `24769562_dariusz`.`Ubezpieczenie` (`idUbezpieczenie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `modelSamochodu`
    FOREIGN KEY (`id`)
    REFERENCES `24769562_dariusz`.`ModelSamochodu` (`idModelSamochodu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `24769562_dariusz`.`Wlasciciel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `24769562_dariusz`.`Wlasciciel` (
  `idWlasciciel` INT NOT NULL AUTO_INCREMENT,
  `Wlasciciel` VARCHAR(45) NULL,
  PRIMARY KEY (`idWlasciciel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `24769562_dariusz`.`Samochod_Wlasciciel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `24769562_dariusz`.`Samochod_Wlasciciel` (
  `idSamochod_Wlasciciel` INT NOT NULL AUTO_INCREMENT,
  `Auto` VARCHAR(45) NULL,
  `Wlasciciel` VARCHAR(45) NULL,
  PRIMARY KEY (`idSamochod_Wlasciciel`),
  CONSTRAINT `Auto`
    FOREIGN KEY (`idSamochod_Wlasciciel`)
    REFERENCES `24769562_dariusz`.`Auta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Wlasciciel`
    FOREIGN KEY (`idSamochod_Wlasciciel`)
    REFERENCES `24769562_dariusz`.`Wlasciciel` (`idWlasciciel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
